In [1]:
#pip instal numpy
#conda install numpy

import numpy as np

In [2]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
np.zeros(5) # 1 solo numero para un arreglo
np.zeros([5,5]) #1 lista o tupla para matriz de ne dimensiones
np.zeros([2,3,4])
np.zeros([1000,200])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
np.eye(10) #matriz identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
np.arange(5,11) #intervalos [ 4,20[

array([ 5,  6,  7,  8,  9, 10])

In [14]:
np.arange(-5,11)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
len(np.ones((12)).reshape(4,3)) #me muestra el tamaño del primer elemento del arreglo

4

In [19]:
np.ones((12)).reshape(4,3).shape #me mustra el numero de dimensiones

(4, 3)

In [35]:
np.arange((12)).reshape(4,3)[1,2]

5

In [36]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [37]:
#resta
a - b

array([5, 5, 5])

In [38]:
#suma
a + b

array([15, 15, 15])

In [40]:
#resta de valores
a - 8
b - 7

array([-2, -2, -2])

In [41]:
#multiplicacion
a * b

array([50, 50, 50])

In [42]:
#division
a / 2

array([5., 5., 5.])

In [45]:
#division de arreglos
a / b

array([2., 2., 2.])

In [74]:
muestra = np.arange(20).reshape(5,2,2)

muestra[respuesta_glucosa]

In [52]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [80]:
mayor = muestra > 5
menor = muestra < 14
par = muestra % 2 == 0

respuesta = (mayor) & (menor) & (par)
muestra[respuesta]

array([ 6,  8, 10, 12])

In [4]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [5]:
B = np.arange(4, 8).reshape(2,2) #creando una matriz
B

array([[4, 5],
       [6, 7]])

In [6]:
A.dot(B) ## aqui estoy haciendo un producto punto

array([[ 6,  7],
       [26, 31]])

In [7]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [8]:
np.dot(A,B) #esta es otra manera de hacer el producto punto

array([[ 6,  7],
       [26, 31]])

In [10]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arreglo_doce.sum() #tenemos la suma de varios elementos de los arreglos

66

In [16]:
arreglo_doce.min()
arreglo_doce.max()

                        #IMPORTANTE
#arreglo_doce[5:].sum() ## aqui puedo elegir una parte del arreglo

11

In [18]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [19]:
arreglo_doce.reshape(3,2,2).sum()

66

In [20]:
arreglo_doce.reshape(3,2,2).sum(axis = 0) #con esto axis estoy sumando por fulas
                                        # con el 0 sumo cada matriz creada

array([[12, 15],
       [18, 21]])

In [21]:
arreglo_doce.reshape(3,2,2).sum(axis = 1) #con el 1 suma los elementos de las matrices pequenias

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [22]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])