In [1]:
import numpy as np

In [5]:
#grados

arreglo_grados = np.array((0,30,45,60,90))
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [6]:
#arreglo en radianes

arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [15]:
numero_random = np.random.randint(
    11) #estamos usando un intervalo de [0:11[
numero_random

2

In [22]:
numero_random_negativo = np.random.randint(
        -9,2 #se pone el negativo primero y hasta donde, igual
                #descolando el ultimo digito
)
numero_random_negativo

-8

In [28]:
arreglo_random = np.random.randint(
    10,20
    ,8
)
arreglo_random

array([16, 10, 14, 15, 16, 14, 14, 18])

In [32]:
np.random.rand(9) #elementos
np.random.rand(3,2) #6 elementos en 3x2

array([[0.51275171, 0.34861958],
       [0.797358  , 0.79079483],
       [0.37992087, 0.89457498]])

In [33]:
np.average(arreglo_random)

14.625

In [34]:
np.mean(arreglo_random)

14.625

In [35]:
np.median(arreglo_random)

14.5

In [36]:
np.std(arreglo_random)

2.1758618981911515

In [37]:
np.var(arreglo_random)

4.734375

In [39]:
arreglo_random.mean() #otra forma de usar estas funciones

14.625